namespace Hendra.Net;

/// <summary>
/// Wire packet identifiers, mirroring wServer/networking/packets/PacketIds.cs.
///
/// The numbering is hand-assigned and non-contiguous — do not infer anything from adjacency.
/// Names follow the server's enum so the two can be diffed mechanically.
/// </summary>
public enum PacketId : byte
{
    Failure = 0,
    UseItem = 1,
    AcceptTrade = 3,
    TradeChanged = 4,
    UsePortal = 6,
    Hello = 9,
    PlayerHit = 10,
    ChangeGuildRank = 11,
    Create = 12,
    SquareHit = 13,
    Reconnect = 14,
    Reskin = 15,
    Move = 16,
    InvDrop = 18,
    EnemyHit = 19,
    CheckCredits = 20,
    NameResult = 22,
    ChooseName = 23,
    GlobalNotification = 24,
    InvSwap = 25,
    Load = 26,
    JoinGuild = 27,
    QuestObjId = 28,
    Goto = 30,
    TradeStart = 31,
    Notification = 33,
    RequestTrade = 34,
    ShootAck = 35,
    AllyShoot = 36,
    ShowEffect = 38,
    CancelTrade = 39,
    ReskinUnlock = 40,
    GuildInvite = 41,
    Update = 42,
    AccountList = 44,
    Teleport = 45,
    Pic = 46,
    PlayerText = 47,
    GuildRemove = 49,
    BuyResult = 50,
    EnemyShoot = 52,
    ChangeTrade = 55,
    File = 56,
    OtherHit = 57,
    InvitedToGuild = 58,
    PlaySound = 59,
    SetCondition = 60,
    VerifyEmail = 61,
    EditAccountList = 62,
    InvResult = 63,
    Pong = 64,
    PlayerShoot = 66,
    NewTick = 68,
    PasswordPrompt = 69,
    MapInfo = 74,
    ClientStat = 75,
    AoeAck = 77,
    TradeAccepted = 78,
    GotoAck = 79,
    TradeRequested = 80,
    CreateSuccess = 81,
    GuildResult = 82,
    Death = 83,
    Ping = 85,
    Escape = 87,
    Aoe = 89,
    UpdateAck = 91,
    ServerPlayerShoot = 92,
    Buy = 93,
    TradeDone = 94,
    CreateGuild = 95,
    Text = 96,
    Damage = 97,
    GroundDamage = 98,
    MarketCommand = 99,
    MarketResult = 100,
    SwitchMusic = 106,
    SetFocus = 108,
    ServerFull = 110,
    QueuePing = 111,
    QueuePong = 112,

    /// <summary>
    /// Client-only in this fork: the AS3 client maps id 155 to GoToQuestRoom, but the server's enum
    /// has no such member and no handler is registered, so it is dropped on arrival.
    /// </summary>
    GoToQuestRoom = 155,

    KeyInfoRequest = 151,
    KeyInfoResponse = 152,
    QoLAction = 165,
    PrestigeRequest = 168,
    PrestigeBuyRequest = 169,
    WeeklyQuestRedeem = 170,
}
