[package]
name = "hendra-sim"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hendra-content = { path = "../content" }
hendra-net = { path = "../net" }
hendra-behavior = { path = "../behavior" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
hendra-behavior = { path = "../behavior" }
