/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_enemy = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_state = 5,
  anon_sym_on = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_RPAREN = 10,
  anon_sym_COLON = 11,
  anon_sym_loot = 12,
  sym_duration = 13,
  sym_number = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_string_token1 = 16,
  sym_escape = 17,
  sym_comment = 18,
  sym_source_file = 19,
  sym_enemy = 20,
  sym_enemy_body = 21,
  sym__item = 22,
  sym_state = 23,
  sym_block = 24,
  sym_behaviour = 25,
  sym_transition = 26,
  sym_call = 27,
  sym_arguments = 28,
  sym_argument = 29,
  sym__value = 30,
  sym_loot_table = 31,
  sym_loot_body = 32,
  sym_loot_entry = 33,
  sym_string = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_enemy_body_repeat1 = 36,
  aux_sym_block_repeat1 = 37,
  aux_sym_arguments_repeat1 = 38,
  aux_sym_loot_body_repeat1 = 39,
  aux_sym_string_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_enemy] = "enemy",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_state] = "state",
  [anon_sym_on] = "on",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_loot] = "loot",
  [sym_duration] = "duration",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape] = "escape",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_enemy] = "enemy",
  [sym_enemy_body] = "enemy_body",
  [sym__item] = "_item",
  [sym_state] = "state",
  [sym_block] = "block",
  [sym_behaviour] = "behaviour",
  [sym_transition] = "transition",
  [sym_call] = "call",
  [sym_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym__value] = "_value",
  [sym_loot_table] = "loot_table",
  [sym_loot_body] = "loot_body",
  [sym_loot_entry] = "loot_entry",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_enemy_body_repeat1] = "enemy_body_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_loot_body_repeat1] = "loot_body_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_enemy] = anon_sym_enemy,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_state] = anon_sym_state,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_loot] = anon_sym_loot,
  [sym_duration] = sym_duration,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape] = sym_escape,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_enemy] = sym_enemy,
  [sym_enemy_body] = sym_enemy_body,
  [sym__item] = sym__item,
  [sym_state] = sym_state,
  [sym_block] = sym_block,
  [sym_behaviour] = sym_behaviour,
  [sym_transition] = sym_transition,
  [sym_call] = sym_call,
  [sym_arguments] = sym_arguments,
  [sym_argument] = sym_argument,
  [sym__value] = sym__value,
  [sym_loot_table] = sym_loot_table,
  [sym_loot_body] = sym_loot_body,
  [sym_loot_entry] = sym_loot_entry,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_enemy_body_repeat1] = aux_sym_enemy_body_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_loot_body_repeat1] = aux_sym_loot_body_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_enemy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loot] = {
    .visible = true,
    .named = false,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_enemy] = {
    .visible = true,
    .named = true,
  },
  [sym_enemy_body] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_state] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_behaviour] = {
    .visible = true,
    .named = true,
  },
  [sym_transition] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_loot_table] = {
    .visible = true,
    .named = true,
  },
  [sym_loot_body] = {
    .visible = true,
    .named = true,
  },
  [sym_loot_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enemy_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_loot_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_call = 2,
  field_condition = 3,
  field_name = 4,
  field_target = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_call] = "call",
  [field_condition] = "condition",
  [field_name] = "name",
  [field_target] = "target",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_call, 0},
  [4] =
    {field_body, 1},
  [5] =
    {field_body, 1},
    {field_call, 0},
  [7] =
    {field_value, 0},
  [8] =
    {field_condition, 1},
    {field_target, 3},
  [10] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 21,
        '#', 27,
        '(', 13,
        ')', 15,
        ',', 14,
        '-', 3,
        '.', 6,
        '/', 4,
        ':', 16,
        '\\', 7,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) ADVANCE(22);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '>') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 21,
        '#', 27,
        '(', 13,
        ')', 15,
        ',', 14,
        '-', 3,
        '.', 6,
        '/', 4,
        ':', 16,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) ADVANCE(22);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'l') ADVANCE(2);
      if (lookahead == 'o') ADVANCE(3);
      if (lookahead == 's') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'y') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_loot);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_enemy);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_state);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_enemy] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_state] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_loot] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym_enemy] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_enemy] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 1,
      anon_sym_state,
    ACTIONS(15), 1,
      anon_sym_on,
    ACTIONS(17), 1,
      anon_sym_loot,
    STATE(12), 1,
      sym_call,
    STATE(3), 6,
      sym__item,
      sym_state,
      sym_behaviour,
      sym_transition,
      sym_loot_table,
      aux_sym_enemy_body_repeat1,
  [30] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_state,
    ACTIONS(15), 1,
      anon_sym_on,
    ACTIONS(17), 1,
      anon_sym_loot,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_call,
    STATE(4), 6,
      sym__item,
      sym_state,
      sym_behaviour,
      sym_transition,
      sym_loot_table,
      aux_sym_enemy_body_repeat1,
  [60] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(24), 1,
      anon_sym_RBRACE,
    ACTIONS(26), 1,
      anon_sym_state,
    ACTIONS(29), 1,
      anon_sym_on,
    ACTIONS(32), 1,
      anon_sym_loot,
    STATE(12), 1,
      sym_call,
    STATE(4), 6,
      sym__item,
      sym_state,
      sym_behaviour,
      sym_transition,
      sym_loot_table,
      aux_sym_enemy_body_repeat1,
  [90] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_state,
    ACTIONS(15), 1,
      anon_sym_on,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_call,
    STATE(6), 5,
      sym__item,
      sym_state,
      sym_behaviour,
      sym_transition,
      aux_sym_block_repeat1,
  [116] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_state,
    ACTIONS(15), 1,
      anon_sym_on,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_call,
    STATE(7), 5,
      sym__item,
      sym_state,
      sym_behaviour,
      sym_transition,
      aux_sym_block_repeat1,
  [142] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      anon_sym_state,
    ACTIONS(47), 1,
      anon_sym_on,
    STATE(12), 1,
      sym_call,
    STATE(7), 5,
      sym__item,
      sym_state,
      sym_behaviour,
      sym_transition,
      aux_sym_block_repeat1,
  [168] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_arguments,
    ACTIONS(52), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    ACTIONS(50), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [189] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    ACTIONS(62), 1,
      sym_duration,
    ACTIONS(64), 1,
      sym_number,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_argument,
    STATE(50), 2,
      sym__value,
      sym_string,
  [218] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(62), 1,
      sym_duration,
    ACTIONS(64), 1,
      sym_number,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_argument,
    STATE(50), 2,
      sym__value,
      sym_string,
  [244] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(62), 1,
      sym_duration,
    ACTIONS(64), 1,
      sym_number,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_argument,
    STATE(50), 2,
      sym__value,
      sym_string,
  [270] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      sym_block,
    ACTIONS(72), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [289] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    ACTIONS(78), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    ACTIONS(82), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [319] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    ACTIONS(86), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    ACTIONS(90), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    ACTIONS(94), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [364] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(62), 1,
      sym_duration,
    ACTIONS(64), 1,
      sym_number,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(49), 1,
      sym_argument,
    STATE(50), 2,
      sym__value,
      sym_string,
  [387] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(100), 1,
      sym_number,
    ACTIONS(98), 2,
      sym_identifier,
      sym_duration,
    STATE(43), 2,
      sym__value,
      sym_string,
  [405] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(102), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [418] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_identifier,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_call,
    STATE(25), 2,
      sym_loot_entry,
      aux_sym_loot_body_repeat1,
  [435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    ACTIONS(110), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [461] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [474] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_identifier,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_call,
    STATE(28), 2,
      sym_loot_entry,
      aux_sym_loot_body_repeat1,
  [491] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(124), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [504] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(128), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [517] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_call,
    STATE(28), 2,
      sym_loot_entry,
      aux_sym_loot_body_repeat1,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [547] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    ACTIONS(141), 4,
      anon_sym_state,
      anon_sym_on,
      anon_sym_loot,
      sym_identifier,
  [560] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_loot_body,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [574] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_enemy,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    STATE(33), 2,
      sym_enemy,
      aux_sym_source_file_repeat1,
  [588] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(153), 1,
      anon_sym_enemy,
    STATE(33), 2,
      sym_enemy,
      aux_sym_source_file_repeat1,
  [602] = 5,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      aux_sym_string_token1,
    ACTIONS(161), 1,
      sym_escape,
    ACTIONS(164), 1,
      sym_comment,
    STATE(34), 1,
      aux_sym_string_repeat1,
  [618] = 5,
    ACTIONS(164), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_DQUOTE,
    ACTIONS(168), 1,
      aux_sym_string_token1,
    ACTIONS(170), 1,
      sym_escape,
    STATE(36), 1,
      aux_sym_string_repeat1,
  [634] = 5,
    ACTIONS(164), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      aux_sym_string_token1,
    ACTIONS(176), 1,
      sym_escape,
    STATE(34), 1,
      aux_sym_string_repeat1,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 3,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_COLON,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [670] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_arguments_repeat1,
  [683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 3,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [692] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_arguments_repeat1,
  [705] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_arguments_repeat1,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [734] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 2,
      ts_builtin_sym_end,
      anon_sym_enemy,
  [742] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(59), 1,
      sym_call,
  [752] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LBRACE,
    STATE(23), 1,
      sym_loot_body,
  [762] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_enemy_body,
  [772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [780] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [788] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      sym_string,
  [798] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      anon_sym_enemy,
  [806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 2,
      ts_builtin_sym_end,
      anon_sym_enemy,
  [814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_block,
  [824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
  [831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_identifier,
  [838] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_identifier,
  [845] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
  [852] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 142,
  [SMALL_STATE(8)] = 168,
  [SMALL_STATE(9)] = 189,
  [SMALL_STATE(10)] = 218,
  [SMALL_STATE(11)] = 244,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 289,
  [SMALL_STATE(14)] = 304,
  [SMALL_STATE(15)] = 319,
  [SMALL_STATE(16)] = 334,
  [SMALL_STATE(17)] = 349,
  [SMALL_STATE(18)] = 364,
  [SMALL_STATE(19)] = 387,
  [SMALL_STATE(20)] = 405,
  [SMALL_STATE(21)] = 418,
  [SMALL_STATE(22)] = 435,
  [SMALL_STATE(23)] = 448,
  [SMALL_STATE(24)] = 461,
  [SMALL_STATE(25)] = 474,
  [SMALL_STATE(26)] = 491,
  [SMALL_STATE(27)] = 504,
  [SMALL_STATE(28)] = 517,
  [SMALL_STATE(29)] = 534,
  [SMALL_STATE(30)] = 547,
  [SMALL_STATE(31)] = 560,
  [SMALL_STATE(32)] = 574,
  [SMALL_STATE(33)] = 588,
  [SMALL_STATE(34)] = 602,
  [SMALL_STATE(35)] = 618,
  [SMALL_STATE(36)] = 634,
  [SMALL_STATE(37)] = 650,
  [SMALL_STATE(38)] = 659,
  [SMALL_STATE(39)] = 670,
  [SMALL_STATE(40)] = 683,
  [SMALL_STATE(41)] = 692,
  [SMALL_STATE(42)] = 705,
  [SMALL_STATE(43)] = 718,
  [SMALL_STATE(44)] = 726,
  [SMALL_STATE(45)] = 734,
  [SMALL_STATE(46)] = 742,
  [SMALL_STATE(47)] = 752,
  [SMALL_STATE(48)] = 762,
  [SMALL_STATE(49)] = 772,
  [SMALL_STATE(50)] = 780,
  [SMALL_STATE(51)] = 788,
  [SMALL_STATE(52)] = 798,
  [SMALL_STATE(53)] = 806,
  [SMALL_STATE(54)] = 814,
  [SMALL_STATE(55)] = 824,
  [SMALL_STATE(56)] = 831,
  [SMALL_STATE(57)] = 838,
  [SMALL_STATE(58)] = 845,
  [SMALL_STATE(59)] = 852,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_enemy_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enemy_body_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_enemy_body_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_enemy_body_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_enemy_body_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 1, 0, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 1, 0, 2),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_behaviour, 1, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_behaviour, 1, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 5, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state, 3, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state, 3, 0, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_behaviour, 2, 0, 5),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_behaviour, 2, 0, 5),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loot_table, 2, 0, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loot_table, 2, 0, 4),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loot_body, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loot_body, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loot_body, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loot_body, 3, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_loot_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_loot_body_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transition, 4, 0, 7),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transition, 4, 0, 7),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loot_entry, 1, 0, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, 0, 8),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loot_entry, 2, 0, 5),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enemy_body, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 6),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enemy, 3, 0, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enemy_body, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_beh(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
